- title: Configuration
  icon: /assets/images/service-icon2.png
  description: Knowledge Base how to configure Raspberry pi, Klipper with Mainsail and much more.
  button_label: Learn More
  url: /blog/
  
- title: Question Answer
  icon: /assets/images/service-icon.png
  description:  Get in touch with the community on the mammoth-3D Discord Server to get answers to your questions.
  button_label: Discord Server
  url: https://discord.gg/UWZZfKS9Dq
  
- title: Documentation
  icon: /assets/images/service-icon3.png
  description:  Explore documentation topics how to assemble or build your mammoth-3D upgrades and mods.
  button_label: Read Docs
  url: /explore-topics/
  